config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'potentials', to: 'users/registrations#new_potential'
    post 'potentials', to: 'users/registrations#create_potential'
  end
  root to: 'mains#index'

  resources :mains do
    resources :potentials
  end

  
end

app/models/main.rb
class Main < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :event
  belongs_to :weight
  belongs_to :number
  belongs_to :sets
  belongs_to :user
  has_one_attached :image
  validates :event_id, numericality: { other_than: 1 }
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
 

  def index
    @mains = Main.order(created_at: :DESC)
    
    @potential = Potential.new(potential_params)
    
  end

  def new
    if user_signed_in?
    @main = Main.new
    else
      redirect_to new_user_session_path
    end
  end

  def edit
    
  end

  def show
    if user_signed_in?
      @mains = Main.all.order(created_at: :DESC)
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @main = Main.new(main_params)
    if @main.save
      redirect_to root_path
    else
      render :new

    end
  end

  def update
    if @main.update(main_params)
      redirect_to main_path 
     else
      render :"mains/edit"
     end
  end

  def destroy
    main = Main.find(params[:id])
    main.destroy
    redirect_to root_path
  end

  private

  def main_params
    params.require(:main).permit(:image, :event_id, :weight_id, :number_id, :sets_id).merge(user_id: current_user.id)
  end

  def potential_params
    #params.require(:potential).permit(:bench_press_id, :squat_id, :deadlift_id).merge(user_id: current_user.id)
  end

end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/mains/edit.html.erb
<div class=edit>
  <div class="sell-btn-contents">
    <%= form_with model:@user, local: true do |f| %>
      今の体重
        <%= f.collection_select(:weight_id, Weight.all, :id, :name, {}, {class:"select-box", id:"user-category"}) %>
       <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    <% end %>
  </div>
</div> 
    

app/views/mains/index.html.erb
<%= render "shared/header" %>
<html>
 <body>
  <div class="title">
   <% if user_signed_in?%>
    <h2><%= link_to current_user.nickname %></h2>
     <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <% else %>
    <h2>
   <%= link_to "新規登録", new_user_registration_path %>
   <%= link_to "ログイン", new_user_session_path %></h2>
  <% end %>
</div>
<div class="menu">
 <li>現在の体重
  kg</li>
</div>
<div class="name">
  <div class="naming">
    <h2><%= link_to "一覧", main_path(@mains) %></h2>
  </div>
   <div class="naming2">
     <h2><%= link_to "今日のトレーニング", new_main_path %></h2>
   </div>
  </div>        
   <main>
    <section>
      <div class="mainimg">
        <image src="/assets/tore.jpeg" alt="メイン画像">
      </div>
    </div>
    </section>
   </div>
  </div>
 </body>
</html>
<div class="col"><hr>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
   <ul class="follow-me">
    <li><a href="https://twitter.com"></a></li>  
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
       <ul class="follow-me2">
    <li><a href="https://www.youtube.com"></a></li>
</div>  
<p id="pagetop"><a href="#">TOP</a></p>  

app/views/mains/new.html.erb
<div class="all2">
 <%= render "shared/header" %>
  <%= form_with model: @main, url:mains_path, local: true do |f| %>
   <label class="select2">
    <div class="text">
     <%= f.file_field :image, id:"item-image" %>
    </div>
  </label>
   <div class="main-box">
    種目
   </div>
   <div class="select">
    <%= f.collection_select(:event_id, Event.all, :id, :name, {}) %>
   </div>
    <div class="main-box">
    重量
    </div>
    <div class="select">
     <%= f.collection_select(:weight_id, Weight.all, :id, :name, {}) %>
    </div>
    <div class="main-box">
    回数
    </div>
    <div class="select">
     <%= f.collection_select(:number_id, Number.all, :id, :name, {}) %>
    </div>
    <div class="main-box">
    セット数
    </div>
    <div class="select">
     <%= f.collection_select(:sets_id, Sets.all, :id, :name, {}) %>
    </div>
    <div class="btn-open">
     <%= f.submit "登録" %>
    </div>
 <% end %>
</div>

 

app/views/mains/show.html.erb
<%= render "shared/header" %>
<div class="yoko">
 <% @mains.each do |main| %>
  <div class="matome" style="background-image: url(<%= main.image %>);">
		<%= image_tag main.image.variant(resize: '300x300'), class: "item-img" if main.image.attached? %>						
  </div>
    <div class="matome2">
     <%= main.event.name %>
      <%= main.weight.name %>kg
		   <%= main.number.name %>回
		  <%= main.sets.name %>セット
		 <%= link_to '削除', main_path(main.id), method: :delete, class:"btn04",data: { confirm: '削除しますか？' } %>
		</div>
	<% end %>
</div>
<%= render "shared/footer" %>